export const FALLBACK_CATEGORIES = [
  {
    id: 'cat1',
    title: 'In-Device Verbal',
    subtitle: 'Imagine stories with your photo friend!',
    photos: [
      {
        id: 'dog',
        label: 'Stuffed Dog',
        src: '/icons/dog.png',
        summary: {
          category: 'category_1',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Who We Are',
          ib_key_concept: 'Perspective',
          concepts_earned: ['Perspective'],
          metaphor: 'This fluffy dog friend has so many feelings inside!',
          role_title: 'Emotion Translator',
          game_mechanic: 'voice_acting',
          round_count: 3,
          round_scenarios: ['warm sunshine on belly', 'tripped and went bump', 'favorite treat arrives'],
          escalation_axis: 'comfortable to excited',
        },
      },
      {
        id: 'cat',
        label: 'Cat',
        src: '/icons/cat.png',
        summary: {
          category: 'category_1',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Who We Are',
          ib_key_concept: 'Reflection',
          concepts_earned: ['Reflection'],
          metaphor: 'This sleepy cat is dreaming the most magical dreams!',
          role_title: 'Dream Whisperer',
          game_mechanic: 'storytelling_chain',
          round_count: 3,
          round_scenarios: ['floating on a cloud in the sky', 'swimming in a milk ocean', 'magical garden of favorites'],
          escalation_axis: 'familiar to fantastical',
        },
      },
      {
        id: 'dinosaur',
        label: 'Dinosaur',
        src: '/icons/dinosaur.png',
        summary: {
          category: 'category_1',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'How the World Works',
          ib_key_concept: 'Change',
          concepts_earned: ['Change'],
          metaphor: 'This amazing dinosaur has traveled through all of history!',
          role_title: 'Time Traveler',
          game_mechanic: 'voice_acting',
          round_count: 3,
          round_scenarios: ['prehistoric jungle', 'rumbling volcano', 'peaceful lake at sunset'],
          escalation_axis: 'everyday to dramatic to peaceful',
        },
      },
    ],
  },
  {
    id: 'cat5',
    title: 'Out-of-Device Collection',
    subtitle: 'Go on a real-world scavenger hunt!',
    photos: [
      {
        id: 'ladybug',
        label: 'Ladybug',
        src: '/icons/ladybug.png',
        summary: {
          category: 'category_5',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How We Express Ourselves',
          ib_key_concept: 'Form',
          concepts_earned: ['Form', 'Connection'],
          metaphor: 'You are a Polka-Dot Patrol Officer!',
          role_title: 'Polka-Dot Patrol Officer',
          round_count: 3,
          collection_criterion: 'Find things with dots, spots, or circles',
          collection_count: 3,
          synthesis_type: 'comparison_chart',
          observation_angle: 'pattern',
          collectible_previews: [
            { label: 'Spotted mushroom', image: '/icons/spotted_mushroom.png' },
            { label: 'Dotted pebble', image: '/icons/dotted_pebble.png' },
            { label: 'Speckled leaf', image: '/icons/speckled_leaf.png' },
            { label: 'Flower with circles', image: '/icons/circle_flower.png' },
          ],
        },
      },
      {
        id: 'dandelion',
        label: 'Dandelion',
        src: '/icons/dandelion.png',
        summary: {
          category: 'category_5',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Connection',
          concepts_earned: ['Connection'],
          metaphor: 'You are a Fluffy Expedition Explorer!',
          role_title: 'Fluffy Expedition Explorer',
          round_count: 3,
          collection_criterion: 'Find things that are fluffy, fuzzy, or soft',
          collection_count: 3,
          synthesis_type: 'naming_story',
          observation_angle: 'texture',
          collectible_previews: [
            { label: 'Fuzzy moss', image: '/icons/fuzzy_moss.png' },
            { label: 'Fluffy seed head', image: '/icons/fluffy_seed.png' },
            { label: 'Soft petal', image: '/icons/soft_petal.png' },
            { label: 'Woolly caterpillar', image: '/icons/woolly_caterpillar.png' },
          ],
        },
      },
    ],
  },
];
