import { asset } from '../utils/basePath';

export const FALLBACK_CATEGORIES = [
  {
    id: 'cat1',
    title: 'In-Device Verbal',
    subtitle: 'Imagine stories with your photo friend!',
    photos: [
      {
        id: 'dog',
        label: 'Stuffed Dog',
        src: asset('/icons/dog.png'),
        summary: {
          category: 'category_1',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Who We Are',
          ib_key_concept: 'Perspective',
          concepts_earned: ['Perspective'],
          metaphor: 'This fluffy dog friend has so many feelings inside!',
          role_title: 'Emotion Translator',
          game_mechanic: 'voice_acting',
          round_count: 3,
          round_scenarios: ['warm sunshine on belly', 'tripped and went bump', 'favorite treat arrives'],
          escalation_axis: 'comfortable to excited',
        },
      },
      {
        id: 'cat',
        label: 'Cat',
        src: asset('/icons/cat.png'),
        summary: {
          category: 'category_1',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Who We Are',
          ib_key_concept: 'Reflection',
          concepts_earned: ['Reflection'],
          metaphor: 'This sleepy cat is dreaming the most magical dreams!',
          role_title: 'Dream Whisperer',
          game_mechanic: 'storytelling_chain',
          round_count: 3,
          round_scenarios: ['floating on a cloud in the sky', 'swimming in a milk ocean', 'magical garden of favorites'],
          escalation_axis: 'familiar to fantastical',
        },
      },
      {
        id: 'dinosaur',
        label: 'Dinosaur',
        src: asset('/icons/dinosaur.png'),
        summary: {
          category: 'category_1',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'How the World Works',
          ib_key_concept: 'Change',
          concepts_earned: ['Change'],
          metaphor: 'This amazing dinosaur has traveled through all of history!',
          role_title: 'Time Traveler',
          game_mechanic: 'voice_acting',
          round_count: 3,
          round_scenarios: ['prehistoric jungle', 'rumbling volcano', 'peaceful lake at sunset'],
          escalation_axis: 'everyday to dramatic to peaceful',
        },
      },
      {
        id: 'bicycle',
        label: 'Bicycle',
        src: asset('/icons/bicycle.png'),
        summary: {
          category: 'category_1',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How the World Works',
          ib_key_concept: 'Function',
          concepts_earned: ['Function', 'Connection'],
          metaphor: 'The child becomes a Bike Whisperer who can hear what the bicycle feels!',
          role_title: 'Bike Whisperer',
          game_mechanic: 'voice_acting',
          round_count: 3,
          round_scenarios: ['zooming downhill', 'getting a flat tire', 'discovering a new path'],
          escalation_axis: 'from pure physical excitement to facing a problem, to exploring the unknown',
        },
      },
      {
        id: 'green_apple',
        label: 'Green Apple',
        src: asset('/icons/green_apple.png'),
        summary: {
          category: 'category_1',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Connection',
          concepts_earned: ['Connection', 'Perspective'],
          metaphor: 'The child becomes an Apple Prediction Scientist!',
          role_title: 'Apple Prediction Scientist',
          game_mechanic: 'prediction_game',
          round_count: 3,
          round_scenarios: ['Taking a big bite', 'Leaving it on the counter for a week', 'Slicing the apple in half'],
          escalation_axis: 'Immediate sensory reaction to long-term changes and hidden structures',
        },
      },
      {
        id: 'playground',
        label: 'Playground',
        src: asset('/icons/playground.png'),
        summary: {
          category: 'category_1',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'Who We Are',
          ib_key_concept: 'Perspective',
          concepts_earned: ['Perspective', 'Function'],
          metaphor: 'Speak for each piece of playground equipment!',
          role_title: 'Playground Feelings Reporter',
          game_mechanic: 'voice_acting',
          round_count: 3,
          round_scenarios: ['The Happy Swing in the sun', 'The Hot Slide baking in summer', 'The Lonely Monkey Bars in the rain'],
          escalation_axis: 'Familiar joy to physical discomfort to emotional loneliness',
        },
      },
      {
        id: 'stop_sign',
        label: 'Stop Sign',
        src: asset('/icons/stop_sign.png'),
        summary: {
          category: 'category_1',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Responsibility',
          concepts_earned: ['Responsibility', 'Function'],
          metaphor: 'The stop sign is a superhero for the street!',
          role_title: 'Safety Solver',
          game_mechanic: 'helper_hotline',
          round_count: 3,
          round_scenarios: ['A driver in a big hurry', 'A kid is still walking across', 'Two cars arrive at the same time'],
          escalation_axis: 'simple rule following to complex social turn-taking',
        },
      },
      {
        id: 'sunflower',
        label: 'Sunflower',
        src: asset('/icons/sunflower.png'),
        summary: {
          category: 'category_1',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How the World Works',
          ib_key_concept: 'Causation',
          concepts_earned: ['Causation', 'Change'],
          metaphor: 'The child becomes a Sunflower Scientist!',
          role_title: 'Sunflower Scientist',
          game_mechanic: 'prediction_game',
          round_count: 3,
          round_scenarios: ['The Morning Sun', 'The Rainy Week', 'The Visiting Bee'],
          escalation_axis: 'simple physical movement to complex biological interaction',
        },
      },
      {
        id: 'city_library',
        label: 'City Library',
        src: asset('/icons/city_library.png'),
        summary: {
          category: 'category_1',
          tier: 'T2',
          ages: '6–8',
          tierLabel: 'Connection Builder',
          ib_theme: 'How the World Works',
          ib_key_concept: 'Function',
          concepts_earned: ['Function', 'Connection'],
          metaphor: 'The library book is a quiet adventurer!',
          role_title: 'Book Journey Narrator',
          game_mechanic: 'storytelling_chain',
          round_count: 4,
          round_scenarios: ['Waiting on the shelf', 'Going to the checkout desk', 'Being read at home', 'The return trip back'],
          escalation_axis: 'From being stationary to moving through the library system',
        },
      },
    ],
  },
  {
    id: 'cat5',
    title: 'Out-of-Device Collection',
    subtitle: 'Go on a real-world scavenger hunt!',
    photos: [
      {
        id: 'ladybug',
        label: 'Ladybug',
        src: asset('/icons/ladybug.png'),
        summary: {
          category: 'category_5',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How We Express Ourselves',
          ib_key_concept: 'Form',
          concepts_earned: ['Form', 'Connection'],
          metaphor: 'You are a Polka-Dot Patrol Officer!',
          role_title: 'Polka-Dot Patrol Officer',
          round_count: 3,
          collection_criterion: 'Find things with dots, spots, or circles',
          collection_count: 3,
          synthesis_type: 'comparison_chart',
          observation_angle: 'pattern',
          collectible_previews: [
            { label: 'Spotted mushroom', image: asset('/icons/spotted_mushroom.png') },
            { label: 'Dotted pebble', image: asset('/icons/dotted_pebble.png') },
            { label: 'Speckled leaf', image: asset('/icons/speckled_leaf.png') },
            { label: 'Flower with circles', image: asset('/icons/circle_flower.png') },
          ],
        },
      },
      {
        id: 'dandelion',
        label: 'Dandelion',
        src: asset('/icons/dandelion.png'),
        summary: {
          category: 'category_5',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Connection',
          concepts_earned: ['Connection'],
          metaphor: 'You are a Fluffy Expedition Explorer!',
          role_title: 'Fluffy Expedition Explorer',
          round_count: 3,
          collection_criterion: 'Find things that are fluffy, fuzzy, or soft',
          collection_count: 3,
          synthesis_type: 'naming_story',
          observation_angle: 'texture',
          collectible_previews: [
            { label: 'Fuzzy moss', image: asset('/icons/fuzzy_moss.png') },
            { label: 'Fluffy seed head', image: asset('/icons/fluffy_seed.png') },
            { label: 'Soft petal', image: asset('/icons/soft_petal.png') },
            { label: 'Woolly caterpillar', image: asset('/icons/woolly_caterpillar.png') },
          ],
        },
      },
      {
        id: 'lion',
        label: 'Lion',
        src: asset('/icons/lion.png'),
        summary: {
          category: 'category_5',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'How We Express Ourselves',
          ib_key_concept: 'Form',
          concepts_earned: ['Form', 'Function'],
          metaphor: 'You are a Brave Things Scout building a Brave Parade!',
          role_title: 'Brave Things Scout',
          round_count: 2,
          collection_criterion: 'Find things that look big, strong, or tough',
          collection_count: 2,
          synthesis_type: 'comparison_chart',
          observation_angle: 'form',
          collectible_previews: [
            { label: 'Big rock', image: asset('/icons/big_rock.png') },
            { label: 'Thick tree trunk', image: asset('/icons/thick_tree_trunk.png') },
            { label: 'Sturdy fence post', image: asset('/icons/sturdy_fence_post.png') },
            { label: 'Thick branch', image: asset('/icons/thick_branch.png') },
          ],
        },
      },
      {
        id: 'crayons',
        label: 'Crayons',
        src: asset('/icons/crayons.png'),
        summary: {
          category: 'category_5',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Connection',
          concepts_earned: ['Connection', 'Perspective'],
          metaphor: 'You are a Color Scout!',
          role_title: 'Color Scout',
          round_count: 2,
          collection_criterion: 'Find things that match your favorite crayon color',
          collection_count: 2,
          synthesis_type: 'naming_story',
          observation_angle: 'color',
          collectible_previews: [
            { label: 'Red flower', image: asset('/icons/red_flower.png') },
            { label: 'Green leaf', image: asset('/icons/green_leaf.png') },
            { label: 'Yellow dandelion', image: asset('/icons/yellow_dandelion.png') },
            { label: 'Blue berry', image: asset('/icons/blue_berry.png') },
          ],
        },
      },
      {
        id: 'raincoat',
        label: 'Raincoat',
        src: asset('/icons/raincoat.png'),
        summary: {
          category: 'category_5',
          tier: 'T0',
          ages: '2–4',
          tierLabel: 'Sensory Explorer',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Connection',
          concepts_earned: ['Connection', 'Function'],
          metaphor: 'You are a Rain Guard!',
          role_title: 'Rain Guard',
          round_count: 2,
          collection_criterion: 'Find things that cover, shelter, or protect from rain',
          collection_count: 2,
          synthesis_type: 'naming_story',
          observation_angle: 'function',
          collectible_previews: [
            { label: 'Big leaf', image: asset('/icons/big_leaf.png') },
            { label: 'Umbrella', image: asset('/icons/umbrella.png') },
            { label: 'Thick bush', image: asset('/icons/thick_bush.png') },
            { label: 'Roof edge', image: asset('/icons/roof_overhang.png') },
          ],
        },
      },
      {
        id: 'eye',
        label: 'Eye',
        src: asset('/icons/eye.png'),
        summary: {
          category: 'category_5',
          tier: 'T2',
          ages: '6–8',
          tierLabel: 'Connection Builder',
          ib_theme: 'Sharing the Planet',
          ib_key_concept: 'Connection',
          concepts_earned: ['Connection', 'Perspective'],
          metaphor: 'You are a Circle Pattern Reporter!',
          role_title: 'Circle Pattern Reporter',
          round_count: 3,
          collection_criterion: 'Find things with eye-like shapes: circles, rings, dots, or concentric patterns',
          collection_count: 3,
          synthesis_type: 'comparison_chart',
          observation_angle: 'pattern',
          collectible_previews: [
            { label: 'Flower center', image: asset('/icons/flower_center.png') },
            { label: 'Bicycle wheel', image: asset('/icons/bicycle_wheel.png') },
            { label: 'Tree stump rings', image: asset('/icons/tree_stump_rings.png') },
            { label: 'Puddle ripples', image: asset('/icons/puddle_ripples.png') },
          ],
        },
      },
      {
        id: 'firefighter',
        label: 'Firefighter',
        src: asset('/icons/firefighter.png'),
        summary: {
          category: 'category_5',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How the World Works',
          ib_key_concept: 'Function',
          concepts_earned: ['Function', 'Responsibility'],
          metaphor: 'You are a Safety Inspector on a mission!',
          role_title: 'Safety Inspector',
          round_count: 3,
          collection_criterion: 'Find things that help keep people safe',
          collection_count: 3,
          synthesis_type: 'comparison_chart',
          observation_angle: 'function',
          collectible_previews: [
            { label: 'Stop sign', image: asset('/icons/stop_sign.png') },
            { label: 'Fire hydrant', image: asset('/icons/fire_hydrant.png') },
            { label: 'Crosswalk lines', image: asset('/icons/crosswalk_paint.png') },
            { label: 'Street light', image: asset('/icons/street_light.png') },
          ],
        },
      },
      {
        id: 'goldfish',
        label: 'Goldfish',
        src: asset('/icons/goldfish.png'),
        summary: {
          category: 'category_5',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How We Express Ourselves',
          ib_key_concept: 'Form',
          concepts_earned: ['Form', 'Connection'],
          metaphor: 'You are a Shimmer Spotter on a safari!',
          role_title: 'Shimmer Spotter',
          round_count: 3,
          collection_criterion: 'Find water creatures or shimmery things nearby',
          collection_count: 3,
          synthesis_type: 'comparison_chart',
          observation_angle: 'form',
          collectible_previews: [
            { label: 'Shiny wet rock', image: asset('/icons/shiny_wet_rock.png') },
            { label: 'Swimming duck', image: asset('/icons/swimming_duck.png') },
            { label: 'Green frog', image: asset('/icons/green_frog.png') },
            { label: 'Sparkly dragonfly', image: asset('/icons/sparkly_dragonfly.png') },
          ],
        },
      },
      {
        id: 'piano',
        label: 'Piano',
        src: asset('/icons/piano.png'),
        summary: {
          category: 'category_5',
          tier: 'T1',
          ages: '4–6',
          tierLabel: 'Function Discoverer',
          ib_theme: 'How We Express Ourselves',
          ib_key_concept: 'Form',
          concepts_earned: ['Form', 'Connection'],
          metaphor: 'You are a Sound Detective on an acoustic investigation!',
          role_title: 'Sound Detective',
          round_count: 3,
          collection_criterion: 'Find things that make interesting sounds when you tap, shake, or blow',
          collection_count: 3,
          synthesis_type: 'sorting_game',
          observation_angle: 'form',
          collectible_previews: [
            { label: 'Metal fence', image: asset('/icons/metal_fence.png') },
            { label: 'Wooden bench', image: asset('/icons/wooden_bench.png') },
            { label: 'Dry leaves', image: asset('/icons/dry_leaves.png') },
            { label: 'Hollow pipe', image: asset('/icons/hollow_pipe.png') },
          ],
        },
      },
    ],
  },
];
