"""Pydantic schema for per-turn Script Agent output."""

from pydantic import BaseModel, Field


class TurnResponse(BaseModel):
    """Single turn of dialogue generated by the Script Agent."""

    dialogue: str = Field(description="The AI dialogue text for this turn")
    tone_marker: str = Field(description="Tone for TTS delivery, e.g. 'excited', 'curious'")
    screen_widget: str = Field(description="Widget type for the device screen")
    screen_widget_params: dict = Field(default_factory=dict, description="Parameters for the screen widget")
    screen_animation: str | None = Field(default=None, description="Animation overlay for the screen")
    sfx_cue: str | None = Field(default=None, description="Sound effect cue ID")
