import BASE from '../utils/basePath';

const GAME_THEMES = {
  dog: {
    characterPng: `${BASE}/icons/dog.png`,
    videoBasePath: `${BASE}/videos/character/mood_changer_dog`,
    videoPrefix: 'dog',
    scenarioBasePath: `${BASE}/videos/scenario/mood_changer_dog`,
    particles: [
      { emoji: '🦴', count: 2, baseSize: 16 },
      { emoji: '🐾', count: 2, baseSize: 14 },
      { emoji: '💙', count: 1, baseSize: 12 },
    ],
    gradient: 'from-blue-100 to-blue-300',
    border: 'border-blue-300/40',
    accent: 'text-blue-800',
    accentBg: 'bg-blue-800/10',
    iconBg: 'bg-white ring-blue-200/60',
    decorations: ['🐾', '🦴'],
  },
  cat: {
    characterPng: `${BASE}/icons/cat.png`,
    videoBasePath: `${BASE}/videos/character/dream_whisperer_cat`,
    videoPrefix: 'cat',
    scenarioBasePath: `${BASE}/videos/scenario/dream_whisperer_cat`,
    particles: [
      { emoji: '⭐', count: 1, baseSize: 14 },
      { emoji: '🌙', count: 1, baseSize: 16 },
      { emoji: '✨', count: 2, baseSize: 12 },
      { emoji: '💜', count: 1, baseSize: 14 },
    ],
    gradient: 'from-violet-100 to-violet-300',
    border: 'border-violet-300/40',
    accent: 'text-violet-800',
    accentBg: 'bg-violet-800/10',
    iconBg: 'bg-white ring-violet-200/60',
    decorations: ['🌙', '✨'],
  },
  dinosaur: {
    characterPng: `${BASE}/icons/dinosaur.png`,
    videoBasePath: `${BASE}/videos/character/time_machine_dinosaur`,
    videoPrefix: 'dinosaur',
    scenarioBasePath: `${BASE}/videos/scenario/time_machine_dinosaur`,
    particles: [
      { emoji: '🌿', count: 1, baseSize: 14 },
      { emoji: '🌋', count: 1, baseSize: 16 },
      { emoji: '🦶', count: 1, baseSize: 14 },
      { emoji: '🧡', count: 1, baseSize: 12 },
    ],
    gradient: 'from-amber-50 to-amber-300',
    border: 'border-amber-300/40',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-800/10',
    iconBg: 'bg-white ring-amber-200/60',
    decorations: ['🌋', '🦴'],
  },
  ladybug: {
    characterPng: `${BASE}/icons/ladybug.png`,
    gradient: 'from-red-100 to-red-300',
    border: 'border-red-300/40',
    accent: 'text-red-800',
    accentBg: 'bg-red-800/10',
    iconBg: 'bg-white ring-red-200/60',
    decorations: ['🍄', '🌺'],
  },
  dandelion: {
    characterPng: `${BASE}/icons/dandelion.png`,
    gradient: 'from-yellow-50 to-yellow-300',
    border: 'border-yellow-300/40',
    accent: 'text-yellow-800',
    accentBg: 'bg-yellow-800/10',
    iconBg: 'bg-white ring-yellow-200/60',
    decorations: ['🌾', '💨'],
  },
  bicycle: {
    characterPng: `${BASE}/icons/bicycle.png`,
    gradient: 'from-sky-100 to-sky-300',
    border: 'border-sky-300/40',
    accent: 'text-sky-800',
    accentBg: 'bg-sky-800/10',
    iconBg: 'bg-white ring-sky-200/60',
    decorations: ['🚲', '💨'],
  },
  city_library: {
    characterPng: `${BASE}/icons/city_library.png`,
    gradient: 'from-teal-100 to-teal-300',
    border: 'border-teal-300/40',
    accent: 'text-teal-800',
    accentBg: 'bg-teal-800/10',
    iconBg: 'bg-white ring-teal-200/60',
    decorations: ['📚', '🏛️'],
  },
  green_apple: {
    characterPng: `${BASE}/icons/green_apple.png`,
    gradient: 'from-lime-100 to-lime-300',
    border: 'border-lime-300/40',
    accent: 'text-lime-800',
    accentBg: 'bg-lime-800/10',
    iconBg: 'bg-white ring-lime-200/60',
    decorations: ['🍏', '🔬'],
  },
  playground: {
    characterPng: `${BASE}/icons/playground.png`,
    gradient: 'from-orange-100 to-orange-300',
    border: 'border-orange-300/40',
    accent: 'text-orange-800',
    accentBg: 'bg-orange-800/10',
    iconBg: 'bg-white ring-orange-200/60',
    decorations: ['🎢', '☀️'],
  },
  stop_sign: {
    characterPng: `${BASE}/icons/stop_sign.png`,
    gradient: 'from-rose-100 to-rose-300',
    border: 'border-rose-300/40',
    accent: 'text-rose-800',
    accentBg: 'bg-rose-800/10',
    iconBg: 'bg-white ring-rose-200/60',
    decorations: ['🛑', '🦺'],
  },
  sunflower: {
    characterPng: `${BASE}/icons/sunflower.png`,
    gradient: 'from-amber-100 to-amber-300',
    border: 'border-amber-300/40',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-800/10',
    iconBg: 'bg-white ring-amber-200/60',
    decorations: ['🌻', '🐝'],
  },
  lion: {
    characterPng: `${BASE}/icons/lion.png`,
    gradient: 'from-yellow-100 to-yellow-300',
    border: 'border-yellow-300/40',
    accent: 'text-yellow-800',
    accentBg: 'bg-yellow-800/10',
    iconBg: 'bg-white ring-yellow-200/60',
    decorations: ['🦁', '💪'],
  },
  eye: {
    characterPng: `${BASE}/icons/eye.png`,
    gradient: 'from-indigo-100 to-indigo-300',
    border: 'border-indigo-300/40',
    accent: 'text-indigo-800',
    accentBg: 'bg-indigo-800/10',
    iconBg: 'bg-white ring-indigo-200/60',
    decorations: ['👁️', '🔍'],
  },
  crayons: {
    characterPng: `${BASE}/icons/crayons.png`,
    gradient: 'from-pink-100 to-pink-300',
    border: 'border-pink-300/40',
    accent: 'text-pink-800',
    accentBg: 'bg-pink-800/10',
    iconBg: 'bg-white ring-pink-200/60',
    decorations: ['🖍️', '🌈'],
  },
  firefighter: {
    characterPng: `${BASE}/icons/firefighter.png`,
    gradient: 'from-red-100 to-red-300',
    border: 'border-red-300/40',
    accent: 'text-red-800',
    accentBg: 'bg-red-800/10',
    iconBg: 'bg-white ring-red-200/60',
    decorations: ['🚒', '🧯'],
  },
  raincoat: {
    characterPng: `${BASE}/icons/raincoat.png`,
    gradient: 'from-cyan-100 to-cyan-300',
    border: 'border-cyan-300/40',
    accent: 'text-cyan-800',
    accentBg: 'bg-cyan-800/10',
    iconBg: 'bg-white ring-cyan-200/60',
    decorations: ['🌧️', '☂️'],
  },
  goldfish: {
    characterPng: `${BASE}/icons/goldfish.png`,
    gradient: 'from-orange-100 to-orange-300',
    border: 'border-orange-300/40',
    accent: 'text-orange-800',
    accentBg: 'bg-orange-800/10',
    iconBg: 'bg-white ring-orange-200/60',
    decorations: ['🐟', '✨'],
  },
  piano: {
    characterPng: `${BASE}/icons/piano.png`,
    gradient: 'from-slate-100 to-slate-300',
    border: 'border-slate-300/40',
    accent: 'text-slate-800',
    accentBg: 'bg-slate-800/10',
    iconBg: 'bg-white ring-slate-200/60',
    decorations: ['🎹', '🎵'],
  },
};

// Maps round_scenario text → video filename slug for scenario clips
const SCENARIO_SLUGS = {
  mood_changer_dog: {
    'warm sunshine on belly': 'warm_sunshine',
    'tripped and went bump': 'tripped_bump',
    'favorite treat arrives': 'favorite_treat',
    'sees a butterfly flying by': 'butterfly',
    'hears thunder outside': 'thunder',
    'best friend comes to visit': 'best_friend',
    'bath time surprise': 'bath_time',
    'found a muddy puddle': 'muddy_puddle',
  },
  dream_whisperer_cat: {
    'floating on a cloud in the sky': 'floating_cloud',
    'swimming in a milk ocean': 'milk_ocean',
    'magical garden of favorites': 'magical_garden',
    'chasing a glowing star through the dark': 'glowing_star',
    'riding on a giant friendly bird': 'giant_bird',
    'exploring a castle made of yarn balls': 'yarn_castle',
    'bouncing on a rainbow bridge': 'rainbow_bridge',
    'hiding in a cozy cave of pillows': 'pillow_cave',
  },
  time_machine_dinosaur: {
    'prehistoric jungle': 'prehistoric_jungle',
    'rumbling volcano': 'rumbling_volcano',
    'peaceful lake at sunset': 'lake_sunset',
    'a snowy mountain top': 'snowy_mountain',
    'a dark spooky cave': 'spooky_cave',
    'a field of giant flowers': 'giant_flowers',
    'a stormy ocean beach': 'stormy_beach',
    'meeting another friendly dinosaur': 'friendly_dinosaur',
  },
};

export function getScenarioSlug(activityType, scenarioText) {
  const slugs = SCENARIO_SLUGS[activityType];
  if (!slugs || !scenarioText) return null;
  return slugs[scenarioText] || null;
}

const DEFAULT_THEME = GAME_THEMES.dog;

export function getThemeForEntity(entity) {
  if (!entity) return DEFAULT_THEME;
  const key = entity.toLowerCase();
  return GAME_THEMES[key] || DEFAULT_THEME;
}
